# ===================================
# Avalon Stack pour Portainer
# ===================================
#
# Instructions:
# 1. Dans Portainer, allez dans Stacks → Add stack
# 2. Copiez-collez ce fichier dans le Web editor
# 3. Configurez les variables d'environnement ci-dessous
# 4. Cliquez sur "Deploy the stack"
#
# Variables d'environnement requises:
# - POSTGRES_USER
# - POSTGRES_PASSWORD (IMPORTANT: Changez-moi!)
# - POSTGRES_DB
# - JWT_SECRET (IMPORTANT: Changez-moi!)
# - DISCORD_WEBHOOK_URL (optionnel)
# - NUXT_PUBLIC_API_BASE
# ===================================

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-avalon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-avalon}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5454}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-avalon}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - avalon-network

  collector:
    image: registry.williamloree.fr/collector:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://${POSTGRES_USER:-avalon}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-avalon}
      JWT_SECRET: ${JWT_SECRET}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL:-}
      DISCORD_ENABLED: ${DISCORD_ENABLED:-false}
    ports:
      - "${COLLECTOR_PORT:-4400}:4000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - collector_logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - avalon-network

  frontend:
    image: registry.williamloree.fr/avalon-app:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE:-http://localhost:4400}
    ports:
      - "${FRONTEND_PORT:-3300}:3000"
    depends_on:
      collector:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - avalon-network

networks:
  avalon-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  collector_logs:
    driver: local
